// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

///<<< BEGIN WRITING YOUR CODE FILE_INIT
using Ranger;
using UnityEngine;

///<<< END WRITING YOUR CODE

public class iTarget : behaviac.Agent
///<<< BEGIN WRITING YOUR CODE iTarget
, IAgent
///<<< END WRITING YOUR CODE
{
    ///<<< BEGIN WRITING YOUR CODE CLASS_PART
    public LayerMask DetectMask {
        get {
            throw new NotImplementedException();
        }

        set {
            throw new NotImplementedException();
        }
    }

    public int layer {
        get {
            throw new NotImplementedException();
        }
    }

    ///<<< END WRITING YOUR CODE

}

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

